package org.haiku.haikudepotserver.dataobjects.auto;



/**
 * This class was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public class _HaikuDepot {

    public static final String SEARCH_PKG_VERSIONS_QUERYNAME = "SearchPkgVersions";
}