package org.haiku.haikudepotserver.dataobjects.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.sql.Timestamp;

import org.apache.cayenne.exp.property.DateProperty;
import org.apache.cayenne.exp.property.EntityProperty;
import org.apache.cayenne.exp.property.PropertyFactory;
import org.apache.cayenne.exp.property.StringProperty;
import org.haiku.haikudepotserver.dataobjects.Job;
import org.haiku.haikudepotserver.dataobjects.JobDataEncoding;
import org.haiku.haikudepotserver.dataobjects.JobDataMediaType;
import org.haiku.haikudepotserver.dataobjects.JobDataType;
import org.haiku.haikudepotserver.dataobjects.support.AbstractDataObject;

/**
 * Class _JobData was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _JobData extends AbstractDataObject {

    private static final long serialVersionUID = 1L;

    public static final String ID_PK_COLUMN = "id";

    public static final StringProperty<String> CODE = PropertyFactory.createString("code", String.class);
    public static final DateProperty<Timestamp> CREATE_TIMESTAMP = PropertyFactory.createDate("createTimestamp", Timestamp.class);
    public static final DateProperty<Timestamp> MODIFY_TIMESTAMP = PropertyFactory.createDate("modifyTimestamp", Timestamp.class);
    public static final StringProperty<String> STORAGE_CODE = PropertyFactory.createString("storageCode", String.class);
    public static final StringProperty<String> USE_CODE = PropertyFactory.createString("useCode", String.class);
    public static final EntityProperty<Job> JOB = PropertyFactory.createEntity("job", Job.class);
    public static final EntityProperty<JobDataEncoding> JOB_DATA_ENCODING = PropertyFactory.createEntity("jobDataEncoding", JobDataEncoding.class);
    public static final EntityProperty<JobDataMediaType> JOB_DATA_MEDIA_TYPE = PropertyFactory.createEntity("jobDataMediaType", JobDataMediaType.class);
    public static final EntityProperty<JobDataType> JOB_DATA_TYPE = PropertyFactory.createEntity("jobDataType", JobDataType.class);

    protected String code;
    protected Timestamp createTimestamp;
    protected Timestamp modifyTimestamp;
    protected String storageCode;
    protected String useCode;

    protected Object job;
    protected Object jobDataEncoding;
    protected Object jobDataMediaType;
    protected Object jobDataType;

    public void setCode(String code) {
        beforePropertyWrite("code", this.code, code);
        this.code = code;
    }

    public String getCode() {
        beforePropertyRead("code");
        return this.code;
    }

    public void setCreateTimestamp(Timestamp createTimestamp) {
        beforePropertyWrite("createTimestamp", this.createTimestamp, createTimestamp);
        this.createTimestamp = createTimestamp;
    }

    public Timestamp getCreateTimestamp() {
        beforePropertyRead("createTimestamp");
        return this.createTimestamp;
    }

    public void setModifyTimestamp(Timestamp modifyTimestamp) {
        beforePropertyWrite("modifyTimestamp", this.modifyTimestamp, modifyTimestamp);
        this.modifyTimestamp = modifyTimestamp;
    }

    public Timestamp getModifyTimestamp() {
        beforePropertyRead("modifyTimestamp");
        return this.modifyTimestamp;
    }

    public void setStorageCode(String storageCode) {
        beforePropertyWrite("storageCode", this.storageCode, storageCode);
        this.storageCode = storageCode;
    }

    public String getStorageCode() {
        beforePropertyRead("storageCode");
        return this.storageCode;
    }

    public void setUseCode(String useCode) {
        beforePropertyWrite("useCode", this.useCode, useCode);
        this.useCode = useCode;
    }

    public String getUseCode() {
        beforePropertyRead("useCode");
        return this.useCode;
    }

    public void setJob(Job job) {
        setToOneTarget("job", job, true);
    }

    public Job getJob() {
        return (Job)readProperty("job");
    }

    public void setJobDataEncoding(JobDataEncoding jobDataEncoding) {
        setToOneTarget("jobDataEncoding", jobDataEncoding, true);
    }

    public JobDataEncoding getJobDataEncoding() {
        return (JobDataEncoding)readProperty("jobDataEncoding");
    }

    public void setJobDataMediaType(JobDataMediaType jobDataMediaType) {
        setToOneTarget("jobDataMediaType", jobDataMediaType, true);
    }

    public JobDataMediaType getJobDataMediaType() {
        return (JobDataMediaType)readProperty("jobDataMediaType");
    }

    public void setJobDataType(JobDataType jobDataType) {
        setToOneTarget("jobDataType", jobDataType, true);
    }

    public JobDataType getJobDataType() {
        return (JobDataType)readProperty("jobDataType");
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "code":
                return this.code;
            case "createTimestamp":
                return this.createTimestamp;
            case "modifyTimestamp":
                return this.modifyTimestamp;
            case "storageCode":
                return this.storageCode;
            case "useCode":
                return this.useCode;
            case "job":
                return this.job;
            case "jobDataEncoding":
                return this.jobDataEncoding;
            case "jobDataMediaType":
                return this.jobDataMediaType;
            case "jobDataType":
                return this.jobDataType;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "code":
                this.code = (String)val;
                break;
            case "createTimestamp":
                this.createTimestamp = (Timestamp)val;
                break;
            case "modifyTimestamp":
                this.modifyTimestamp = (Timestamp)val;
                break;
            case "storageCode":
                this.storageCode = (String)val;
                break;
            case "useCode":
                this.useCode = (String)val;
                break;
            case "job":
                this.job = val;
                break;
            case "jobDataEncoding":
                this.jobDataEncoding = val;
                break;
            case "jobDataMediaType":
                this.jobDataMediaType = val;
                break;
            case "jobDataType":
                this.jobDataType = val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.code);
        out.writeObject(this.createTimestamp);
        out.writeObject(this.modifyTimestamp);
        out.writeObject(this.storageCode);
        out.writeObject(this.useCode);
        out.writeObject(this.job);
        out.writeObject(this.jobDataEncoding);
        out.writeObject(this.jobDataMediaType);
        out.writeObject(this.jobDataType);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.code = (String)in.readObject();
        this.createTimestamp = (Timestamp)in.readObject();
        this.modifyTimestamp = (Timestamp)in.readObject();
        this.storageCode = (String)in.readObject();
        this.useCode = (String)in.readObject();
        this.job = in.readObject();
        this.jobDataEncoding = in.readObject();
        this.jobDataMediaType = in.readObject();
        this.jobDataType = in.readObject();
    }

}
