package org.haiku.haikudepotserver.dataobjects.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.sql.Timestamp;
import java.util.List;

import org.apache.cayenne.exp.property.DateProperty;
import org.apache.cayenne.exp.property.EntityProperty;
import org.apache.cayenne.exp.property.ListProperty;
import org.apache.cayenne.exp.property.NumericProperty;
import org.apache.cayenne.exp.property.PropertyFactory;
import org.apache.cayenne.exp.property.StringProperty;
import org.haiku.haikudepotserver.dataobjects.JobAssignment;
import org.haiku.haikudepotserver.dataobjects.JobData;
import org.haiku.haikudepotserver.dataobjects.JobType;
import org.haiku.haikudepotserver.dataobjects.support.AbstractDataObject;

/**
 * Class _Job was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Job extends AbstractDataObject {

    private static final long serialVersionUID = 1L;

    public static final String ID_PK_COLUMN = "id";

    public static final DateProperty<Timestamp> CANCEL_TIMESTAMP = PropertyFactory.createDate("cancelTimestamp", Timestamp.class);
    public static final StringProperty<String> CODE = PropertyFactory.createString("code", String.class);
    public static final DateProperty<Timestamp> CREATE_TIMESTAMP = PropertyFactory.createDate("createTimestamp", Timestamp.class);
    public static final DateProperty<Timestamp> EXPIRY_TIMESTAMP = PropertyFactory.createDate("expiryTimestamp", Timestamp.class);
    public static final DateProperty<Timestamp> FAIL_TIMESTAMP = PropertyFactory.createDate("failTimestamp", Timestamp.class);
    public static final DateProperty<Timestamp> FINISH_TIMESTAMP = PropertyFactory.createDate("finishTimestamp", Timestamp.class);
    public static final DateProperty<Timestamp> MODIFY_TIMESTAMP = PropertyFactory.createDate("modifyTimestamp", Timestamp.class);
    public static final StringProperty<String> OWNER_USER_NICKNAME = PropertyFactory.createString("ownerUserNickname", String.class);
    public static final NumericProperty<Integer> PROGRESS_PERCENT = PropertyFactory.createNumeric("progressPercent", Integer.class);
    public static final DateProperty<Timestamp> QUEUE_TIMESTAMP = PropertyFactory.createDate("queueTimestamp", Timestamp.class);
    public static final StringProperty<String> SPECIFICATION = PropertyFactory.createString("specification", String.class);
    public static final DateProperty<Timestamp> START_TIMESTAMP = PropertyFactory.createDate("startTimestamp", Timestamp.class);
    public static final EntityProperty<JobAssignment> JOB_ASSIGNMENT = PropertyFactory.createEntity("jobAssignment", JobAssignment.class);
    public static final ListProperty<JobData> JOB_DATAS = PropertyFactory.createList("jobDatas", JobData.class);
    public static final EntityProperty<JobType> JOB_TYPE = PropertyFactory.createEntity("jobType", JobType.class);

    protected Timestamp cancelTimestamp;
    protected String code;
    protected Timestamp createTimestamp;
    protected Timestamp expiryTimestamp;
    protected Timestamp failTimestamp;
    protected Timestamp finishTimestamp;
    protected Timestamp modifyTimestamp;
    protected String ownerUserNickname;
    protected Integer progressPercent;
    protected Timestamp queueTimestamp;
    protected String specification;
    protected Timestamp startTimestamp;

    protected Object jobAssignment;
    protected Object jobDatas;
    protected Object jobType;

    public void setCancelTimestamp(Timestamp cancelTimestamp) {
        beforePropertyWrite("cancelTimestamp", this.cancelTimestamp, cancelTimestamp);
        this.cancelTimestamp = cancelTimestamp;
    }

    public Timestamp getCancelTimestamp() {
        beforePropertyRead("cancelTimestamp");
        return this.cancelTimestamp;
    }

    public void setCode(String code) {
        beforePropertyWrite("code", this.code, code);
        this.code = code;
    }

    public String getCode() {
        beforePropertyRead("code");
        return this.code;
    }

    public void setCreateTimestamp(Timestamp createTimestamp) {
        beforePropertyWrite("createTimestamp", this.createTimestamp, createTimestamp);
        this.createTimestamp = createTimestamp;
    }

    public Timestamp getCreateTimestamp() {
        beforePropertyRead("createTimestamp");
        return this.createTimestamp;
    }

    public void setExpiryTimestamp(Timestamp expiryTimestamp) {
        beforePropertyWrite("expiryTimestamp", this.expiryTimestamp, expiryTimestamp);
        this.expiryTimestamp = expiryTimestamp;
    }

    public Timestamp getExpiryTimestamp() {
        beforePropertyRead("expiryTimestamp");
        return this.expiryTimestamp;
    }

    public void setFailTimestamp(Timestamp failTimestamp) {
        beforePropertyWrite("failTimestamp", this.failTimestamp, failTimestamp);
        this.failTimestamp = failTimestamp;
    }

    public Timestamp getFailTimestamp() {
        beforePropertyRead("failTimestamp");
        return this.failTimestamp;
    }

    public void setFinishTimestamp(Timestamp finishTimestamp) {
        beforePropertyWrite("finishTimestamp", this.finishTimestamp, finishTimestamp);
        this.finishTimestamp = finishTimestamp;
    }

    public Timestamp getFinishTimestamp() {
        beforePropertyRead("finishTimestamp");
        return this.finishTimestamp;
    }

    public void setModifyTimestamp(Timestamp modifyTimestamp) {
        beforePropertyWrite("modifyTimestamp", this.modifyTimestamp, modifyTimestamp);
        this.modifyTimestamp = modifyTimestamp;
    }

    public Timestamp getModifyTimestamp() {
        beforePropertyRead("modifyTimestamp");
        return this.modifyTimestamp;
    }

    public void setOwnerUserNickname(String ownerUserNickname) {
        beforePropertyWrite("ownerUserNickname", this.ownerUserNickname, ownerUserNickname);
        this.ownerUserNickname = ownerUserNickname;
    }

    public String getOwnerUserNickname() {
        beforePropertyRead("ownerUserNickname");
        return this.ownerUserNickname;
    }

    public void setProgressPercent(Integer progressPercent) {
        beforePropertyWrite("progressPercent", this.progressPercent, progressPercent);
        this.progressPercent = progressPercent;
    }

    public Integer getProgressPercent() {
        beforePropertyRead("progressPercent");
        return this.progressPercent;
    }

    public void setQueueTimestamp(Timestamp queueTimestamp) {
        beforePropertyWrite("queueTimestamp", this.queueTimestamp, queueTimestamp);
        this.queueTimestamp = queueTimestamp;
    }

    public Timestamp getQueueTimestamp() {
        beforePropertyRead("queueTimestamp");
        return this.queueTimestamp;
    }

    public void setSpecification(String specification) {
        beforePropertyWrite("specification", this.specification, specification);
        this.specification = specification;
    }

    public String getSpecification() {
        beforePropertyRead("specification");
        return this.specification;
    }

    public void setStartTimestamp(Timestamp startTimestamp) {
        beforePropertyWrite("startTimestamp", this.startTimestamp, startTimestamp);
        this.startTimestamp = startTimestamp;
    }

    public Timestamp getStartTimestamp() {
        beforePropertyRead("startTimestamp");
        return this.startTimestamp;
    }

    public void setJobAssignment(JobAssignment jobAssignment) {
        setToOneTarget("jobAssignment", jobAssignment, true);
    }

    public JobAssignment getJobAssignment() {
        return (JobAssignment)readProperty("jobAssignment");
    }

    public void addToJobDatas(JobData obj) {
        addToManyTarget("jobDatas", obj, true);
    }

    public void removeFromJobDatas(JobData obj) {
        removeToManyTarget("jobDatas", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<JobData> getJobDatas() {
        return (List<JobData>)readProperty("jobDatas");
    }

    public void setJobType(JobType jobType) {
        setToOneTarget("jobType", jobType, true);
    }

    public JobType getJobType() {
        return (JobType)readProperty("jobType");
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "cancelTimestamp":
                return this.cancelTimestamp;
            case "code":
                return this.code;
            case "createTimestamp":
                return this.createTimestamp;
            case "expiryTimestamp":
                return this.expiryTimestamp;
            case "failTimestamp":
                return this.failTimestamp;
            case "finishTimestamp":
                return this.finishTimestamp;
            case "modifyTimestamp":
                return this.modifyTimestamp;
            case "ownerUserNickname":
                return this.ownerUserNickname;
            case "progressPercent":
                return this.progressPercent;
            case "queueTimestamp":
                return this.queueTimestamp;
            case "specification":
                return this.specification;
            case "startTimestamp":
                return this.startTimestamp;
            case "jobAssignment":
                return this.jobAssignment;
            case "jobDatas":
                return this.jobDatas;
            case "jobType":
                return this.jobType;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "cancelTimestamp":
                this.cancelTimestamp = (Timestamp)val;
                break;
            case "code":
                this.code = (String)val;
                break;
            case "createTimestamp":
                this.createTimestamp = (Timestamp)val;
                break;
            case "expiryTimestamp":
                this.expiryTimestamp = (Timestamp)val;
                break;
            case "failTimestamp":
                this.failTimestamp = (Timestamp)val;
                break;
            case "finishTimestamp":
                this.finishTimestamp = (Timestamp)val;
                break;
            case "modifyTimestamp":
                this.modifyTimestamp = (Timestamp)val;
                break;
            case "ownerUserNickname":
                this.ownerUserNickname = (String)val;
                break;
            case "progressPercent":
                this.progressPercent = (Integer)val;
                break;
            case "queueTimestamp":
                this.queueTimestamp = (Timestamp)val;
                break;
            case "specification":
                this.specification = (String)val;
                break;
            case "startTimestamp":
                this.startTimestamp = (Timestamp)val;
                break;
            case "jobAssignment":
                this.jobAssignment = val;
                break;
            case "jobDatas":
                this.jobDatas = val;
                break;
            case "jobType":
                this.jobType = val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.cancelTimestamp);
        out.writeObject(this.code);
        out.writeObject(this.createTimestamp);
        out.writeObject(this.expiryTimestamp);
        out.writeObject(this.failTimestamp);
        out.writeObject(this.finishTimestamp);
        out.writeObject(this.modifyTimestamp);
        out.writeObject(this.ownerUserNickname);
        out.writeObject(this.progressPercent);
        out.writeObject(this.queueTimestamp);
        out.writeObject(this.specification);
        out.writeObject(this.startTimestamp);
        out.writeObject(this.jobAssignment);
        out.writeObject(this.jobDatas);
        out.writeObject(this.jobType);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.cancelTimestamp = (Timestamp)in.readObject();
        this.code = (String)in.readObject();
        this.createTimestamp = (Timestamp)in.readObject();
        this.expiryTimestamp = (Timestamp)in.readObject();
        this.failTimestamp = (Timestamp)in.readObject();
        this.finishTimestamp = (Timestamp)in.readObject();
        this.modifyTimestamp = (Timestamp)in.readObject();
        this.ownerUserNickname = (String)in.readObject();
        this.progressPercent = (Integer)in.readObject();
        this.queueTimestamp = (Timestamp)in.readObject();
        this.specification = (String)in.readObject();
        this.startTimestamp = (Timestamp)in.readObject();
        this.jobAssignment = in.readObject();
        this.jobDatas = in.readObject();
        this.jobType = in.readObject();
    }

}
