package org.haiku.haikudepotserver.dataobjects.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.sql.Timestamp;

import org.apache.cayenne.exp.property.DateProperty;
import org.apache.cayenne.exp.property.EntityProperty;
import org.apache.cayenne.exp.property.NumericProperty;
import org.apache.cayenne.exp.property.PropertyFactory;
import org.haiku.haikudepotserver.dataobjects.NaturalLanguage;
import org.haiku.haikudepotserver.dataobjects.support.AbstractDataObject;

/**
 * Class _NaturalLanguageUse was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _NaturalLanguageUse extends AbstractDataObject {

    private static final long serialVersionUID = 1L;

    public static final String ID_PK_COLUMN = "id";

    public static final NumericProperty<Long> COUNT = PropertyFactory.createNumeric("count", Long.class);
    public static final DateProperty<Timestamp> CREATE_TIMESTAMP = PropertyFactory.createDate("createTimestamp", Timestamp.class);
    public static final DateProperty<Timestamp> LAST_USE_TIMESTAMP = PropertyFactory.createDate("lastUseTimestamp", Timestamp.class);
    public static final DateProperty<Timestamp> MODIFY_TIMESTAMP = PropertyFactory.createDate("modifyTimestamp", Timestamp.class);
    public static final EntityProperty<NaturalLanguage> NATURAL_LANGUAGE = PropertyFactory.createEntity("naturalLanguage", NaturalLanguage.class);

    protected Long count;
    protected Timestamp createTimestamp;
    protected Timestamp lastUseTimestamp;
    protected Timestamp modifyTimestamp;

    protected Object naturalLanguage;

    public void setCount(Long count) {
        beforePropertyWrite("count", this.count, count);
        this.count = count;
    }

    public Long getCount() {
        beforePropertyRead("count");
        return this.count;
    }

    public void setCreateTimestamp(Timestamp createTimestamp) {
        beforePropertyWrite("createTimestamp", this.createTimestamp, createTimestamp);
        this.createTimestamp = createTimestamp;
    }

    public Timestamp getCreateTimestamp() {
        beforePropertyRead("createTimestamp");
        return this.createTimestamp;
    }

    public void setLastUseTimestamp(Timestamp lastUseTimestamp) {
        beforePropertyWrite("lastUseTimestamp", this.lastUseTimestamp, lastUseTimestamp);
        this.lastUseTimestamp = lastUseTimestamp;
    }

    public Timestamp getLastUseTimestamp() {
        beforePropertyRead("lastUseTimestamp");
        return this.lastUseTimestamp;
    }

    public void setModifyTimestamp(Timestamp modifyTimestamp) {
        beforePropertyWrite("modifyTimestamp", this.modifyTimestamp, modifyTimestamp);
        this.modifyTimestamp = modifyTimestamp;
    }

    public Timestamp getModifyTimestamp() {
        beforePropertyRead("modifyTimestamp");
        return this.modifyTimestamp;
    }

    public void setNaturalLanguage(NaturalLanguage naturalLanguage) {
        setToOneTarget("naturalLanguage", naturalLanguage, true);
    }

    public NaturalLanguage getNaturalLanguage() {
        return (NaturalLanguage)readProperty("naturalLanguage");
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "count":
                return this.count;
            case "createTimestamp":
                return this.createTimestamp;
            case "lastUseTimestamp":
                return this.lastUseTimestamp;
            case "modifyTimestamp":
                return this.modifyTimestamp;
            case "naturalLanguage":
                return this.naturalLanguage;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "count":
                this.count = (Long)val;
                break;
            case "createTimestamp":
                this.createTimestamp = (Timestamp)val;
                break;
            case "lastUseTimestamp":
                this.lastUseTimestamp = (Timestamp)val;
                break;
            case "modifyTimestamp":
                this.modifyTimestamp = (Timestamp)val;
                break;
            case "naturalLanguage":
                this.naturalLanguage = val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.count);
        out.writeObject(this.createTimestamp);
        out.writeObject(this.lastUseTimestamp);
        out.writeObject(this.modifyTimestamp);
        out.writeObject(this.naturalLanguage);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.count = (Long)in.readObject();
        this.createTimestamp = (Timestamp)in.readObject();
        this.lastUseTimestamp = (Timestamp)in.readObject();
        this.modifyTimestamp = (Timestamp)in.readObject();
        this.naturalLanguage = in.readObject();
    }

}
