package org.haiku.haikudepotserver.dataobjects.auto;

import java.util.Date;

import org.apache.cayenne.exp.Property;
import org.haiku.haikudepotserver.dataobjects.Permission;
import org.haiku.haikudepotserver.dataobjects.Pkg;
import org.haiku.haikudepotserver.dataobjects.User;
import org.haiku.haikudepotserver.dataobjects.support.AbstractDataObject;

/**
 * Class _PermissionUserPkg was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _PermissionUserPkg extends AbstractDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<Date> CREATE_TIMESTAMP = Property.create("createTimestamp", Date.class);
    public static final Property<Permission> PERMISSION = Property.create("permission", Permission.class);
    public static final Property<Pkg> PKG = Property.create("pkg", Pkg.class);
    public static final Property<User> USER = Property.create("user", User.class);

    public void setCreateTimestamp(Date createTimestamp) {
        writeProperty("createTimestamp", createTimestamp);
    }
    public Date getCreateTimestamp() {
        return (Date)readProperty("createTimestamp");
    }

    public void setPermission(Permission permission) {
        setToOneTarget("permission", permission, true);
    }

    public Permission getPermission() {
        return (Permission)readProperty("permission");
    }


    public void setPkg(Pkg pkg) {
        setToOneTarget("pkg", pkg, true);
    }

    public Pkg getPkg() {
        return (Pkg)readProperty("pkg");
    }


    public void setUser(User user) {
        setToOneTarget("user", user, true);
    }

    public User getUser() {
        return (User)readProperty("user");
    }


}
