package org.haiku.haikudepotserver.dataobjects.auto;

import org.apache.cayenne.exp.Property;
import org.haiku.haikudepotserver.dataobjects.PkgIcon;
import org.haiku.haikudepotserver.dataobjects.support.AbstractDataObject;

/**
 * Class _PkgIconImage was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _PkgIconImage extends AbstractDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<byte[]> DATA = Property.create("data", byte[].class);
    public static final Property<PkgIcon> PKG_ICON = Property.create("pkgIcon", PkgIcon.class);

    public void setData(byte[] data) {
        writeProperty("data", data);
    }
    public byte[] getData() {
        return (byte[])readProperty("data");
    }

    public void setPkgIcon(PkgIcon pkgIcon) {
        setToOneTarget("pkgIcon", pkgIcon, true);
    }

    public PkgIcon getPkgIcon() {
        return (PkgIcon)readProperty("pkgIcon");
    }


}
