package org.haiku.haikudepotserver.dataobjects.auto;

import org.haiku.haikudepotserver.dataobjects.Pkg;
import org.haiku.haikudepotserver.dataobjects.Prominence;
import org.haiku.haikudepotserver.dataobjects.Repository;
import org.haiku.haikudepotserver.dataobjects.support.AbstractDataObject;

/**
 * Class _PkgProminence was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _PkgProminence extends AbstractDataObject {

    public static final String PKG_PROPERTY = "pkg";
    public static final String PROMINENCE_PROPERTY = "prominence";
    public static final String REPOSITORY_PROPERTY = "repository";

    public static final String ID_PK_COLUMN = "id";

    public void setPkg(Pkg pkg) {
        setToOneTarget(PKG_PROPERTY, pkg, true);
    }

    public Pkg getPkg() {
        return (Pkg)readProperty(PKG_PROPERTY);
    }


    public void setProminence(Prominence prominence) {
        setToOneTarget(PROMINENCE_PROPERTY, prominence, true);
    }

    public Prominence getProminence() {
        return (Prominence)readProperty(PROMINENCE_PROPERTY);
    }


    public void setRepository(Repository repository) {
        setToOneTarget(REPOSITORY_PROPERTY, repository, true);
    }

    public Repository getRepository() {
        return (Repository)readProperty(REPOSITORY_PROPERTY);
    }


}
