package org.haiku.haikudepotserver.dataobjects.auto;

import java.util.List;

import org.apache.cayenne.exp.Property;
import org.haiku.haikudepotserver.dataobjects.MediaType;
import org.haiku.haikudepotserver.dataobjects.Pkg;
import org.haiku.haikudepotserver.dataobjects.PkgIconImage;
import org.haiku.haikudepotserver.dataobjects.support.AbstractDataObject;

/**
 * Class _PkgIcon was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _PkgIcon extends AbstractDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<Integer> SIZE = Property.create("size", Integer.class);
    public static final Property<MediaType> MEDIA_TYPE = Property.create("mediaType", MediaType.class);
    public static final Property<Pkg> PKG = Property.create("pkg", Pkg.class);
    public static final Property<List<PkgIconImage>> PKG_ICON_IMAGES = Property.create("pkgIconImages", List.class);

    public void setSize(Integer size) {
        writeProperty("size", size);
    }
    public Integer getSize() {
        return (Integer)readProperty("size");
    }

    public void setMediaType(MediaType mediaType) {
        setToOneTarget("mediaType", mediaType, true);
    }

    public MediaType getMediaType() {
        return (MediaType)readProperty("mediaType");
    }


    public void setPkg(Pkg pkg) {
        setToOneTarget("pkg", pkg, true);
    }

    public Pkg getPkg() {
        return (Pkg)readProperty("pkg");
    }


    public void addToPkgIconImages(PkgIconImage obj) {
        addToManyTarget("pkgIconImages", obj, true);
    }
    public void removeFromPkgIconImages(PkgIconImage obj) {
        removeToManyTarget("pkgIconImages", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<PkgIconImage> getPkgIconImages() {
        return (List<PkgIconImage>)readProperty("pkgIconImages");
    }


}
