package org.haiku.haikudepotserver.dataobjects.auto;

import java.util.Date;

import org.apache.cayenne.exp.Property;
import org.haiku.haikudepotserver.dataobjects.LocalizationContent;
import org.haiku.haikudepotserver.dataobjects.NaturalLanguage;
import org.haiku.haikudepotserver.dataobjects.PkgVersion;
import org.haiku.haikudepotserver.dataobjects.support.AbstractDataObject;

/**
 * Class _PkgVersionLocalization was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _PkgVersionLocalization extends AbstractDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<Date> CREATE_TIMESTAMP = Property.create("createTimestamp", Date.class);
    public static final Property<Date> MODIFY_TIMESTAMP = Property.create("modifyTimestamp", Date.class);
    public static final Property<LocalizationContent> DESCRIPTION_LOCALIZATION_CONTENT = Property.create("descriptionLocalizationContent", LocalizationContent.class);
    public static final Property<NaturalLanguage> NATURAL_LANGUAGE = Property.create("naturalLanguage", NaturalLanguage.class);
    public static final Property<PkgVersion> PKG_VERSION = Property.create("pkgVersion", PkgVersion.class);
    public static final Property<LocalizationContent> SUMMARY_LOCALIZATION_CONTENT = Property.create("summaryLocalizationContent", LocalizationContent.class);
    public static final Property<LocalizationContent> TITLE_LOCALIZATION_CONTENT = Property.create("titleLocalizationContent", LocalizationContent.class);

    public void setCreateTimestamp(Date createTimestamp) {
        writeProperty("createTimestamp", createTimestamp);
    }
    public Date getCreateTimestamp() {
        return (Date)readProperty("createTimestamp");
    }

    public void setModifyTimestamp(Date modifyTimestamp) {
        writeProperty("modifyTimestamp", modifyTimestamp);
    }
    public Date getModifyTimestamp() {
        return (Date)readProperty("modifyTimestamp");
    }

    public void setDescriptionLocalizationContent(LocalizationContent descriptionLocalizationContent) {
        setToOneTarget("descriptionLocalizationContent", descriptionLocalizationContent, true);
    }

    public LocalizationContent getDescriptionLocalizationContent() {
        return (LocalizationContent)readProperty("descriptionLocalizationContent");
    }


    public void setNaturalLanguage(NaturalLanguage naturalLanguage) {
        setToOneTarget("naturalLanguage", naturalLanguage, true);
    }

    public NaturalLanguage getNaturalLanguage() {
        return (NaturalLanguage)readProperty("naturalLanguage");
    }


    public void setPkgVersion(PkgVersion pkgVersion) {
        setToOneTarget("pkgVersion", pkgVersion, true);
    }

    public PkgVersion getPkgVersion() {
        return (PkgVersion)readProperty("pkgVersion");
    }


    public void setSummaryLocalizationContent(LocalizationContent summaryLocalizationContent) {
        setToOneTarget("summaryLocalizationContent", summaryLocalizationContent, true);
    }

    public LocalizationContent getSummaryLocalizationContent() {
        return (LocalizationContent)readProperty("summaryLocalizationContent");
    }


    public void setTitleLocalizationContent(LocalizationContent titleLocalizationContent) {
        setToOneTarget("titleLocalizationContent", titleLocalizationContent, true);
    }

    public LocalizationContent getTitleLocalizationContent() {
        return (LocalizationContent)readProperty("titleLocalizationContent");
    }


}
