package org.haiku.haikudepotserver.dataobjects.auto;

import java.sql.Timestamp;
import java.util.List;

import org.apache.cayenne.exp.Property;
import org.haiku.haikudepotserver.dataobjects.PermissionUserPkg;
import org.haiku.haikudepotserver.dataobjects.PkgProminence;
import org.haiku.haikudepotserver.dataobjects.PkgSupplement;
import org.haiku.haikudepotserver.dataobjects.PkgUserRatingAggregate;
import org.haiku.haikudepotserver.dataobjects.Publisher;
import org.haiku.haikudepotserver.dataobjects.support.AbstractDataObject;

/**
 * Class _Pkg was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Pkg extends AbstractDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<Boolean> ACTIVE = Property.create("active", Boolean.class);
    public static final Property<Timestamp> CREATE_TIMESTAMP = Property.create("createTimestamp", Timestamp.class);
    public static final Property<Timestamp> MODIFY_TIMESTAMP = Property.create("modifyTimestamp", Timestamp.class);
    public static final Property<String> NAME = Property.create("name", String.class);
    public static final Property<List<PermissionUserPkg>> PERMISSION_USER_PKGS = Property.create("permissionUserPkgs", List.class);
    public static final Property<List<PkgProminence>> PKG_PROMINENCES = Property.create("pkgProminences", List.class);
    public static final Property<PkgSupplement> PKG_SUPPLEMENT = Property.create("pkgSupplement", PkgSupplement.class);
    public static final Property<List<PkgUserRatingAggregate>> PKG_USER_RATING_AGGREGATES = Property.create("pkgUserRatingAggregates", List.class);
    public static final Property<Publisher> PUBLISHER = Property.create("publisher", Publisher.class);

    public void setActive(Boolean active) {
        writeProperty("active", active);
    }
    public Boolean getActive() {
        return (Boolean)readProperty("active");
    }

    public void setCreateTimestamp(Timestamp createTimestamp) {
        writeProperty("createTimestamp", createTimestamp);
    }
    public Timestamp getCreateTimestamp() {
        return (Timestamp)readProperty("createTimestamp");
    }

    public void setModifyTimestamp(Timestamp modifyTimestamp) {
        writeProperty("modifyTimestamp", modifyTimestamp);
    }
    public Timestamp getModifyTimestamp() {
        return (Timestamp)readProperty("modifyTimestamp");
    }

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void addToPermissionUserPkgs(PermissionUserPkg obj) {
        addToManyTarget("permissionUserPkgs", obj, true);
    }
    public void removeFromPermissionUserPkgs(PermissionUserPkg obj) {
        removeToManyTarget("permissionUserPkgs", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<PermissionUserPkg> getPermissionUserPkgs() {
        return (List<PermissionUserPkg>)readProperty("permissionUserPkgs");
    }


    public void addToPkgProminences(PkgProminence obj) {
        addToManyTarget("pkgProminences", obj, true);
    }
    public void removeFromPkgProminences(PkgProminence obj) {
        removeToManyTarget("pkgProminences", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<PkgProminence> getPkgProminences() {
        return (List<PkgProminence>)readProperty("pkgProminences");
    }


    public void setPkgSupplement(PkgSupplement pkgSupplement) {
        setToOneTarget("pkgSupplement", pkgSupplement, true);
    }

    public PkgSupplement getPkgSupplement() {
        return (PkgSupplement)readProperty("pkgSupplement");
    }


    public void addToPkgUserRatingAggregates(PkgUserRatingAggregate obj) {
        addToManyTarget("pkgUserRatingAggregates", obj, true);
    }
    public void removeFromPkgUserRatingAggregates(PkgUserRatingAggregate obj) {
        removeToManyTarget("pkgUserRatingAggregates", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<PkgUserRatingAggregate> getPkgUserRatingAggregates() {
        return (List<PkgUserRatingAggregate>)readProperty("pkgUserRatingAggregates");
    }


    public void setPublisher(Publisher publisher) {
        setToOneTarget("publisher", publisher, true);
    }

    public Publisher getPublisher() {
        return (Publisher)readProperty("publisher");
    }


}
