package org.haiku.haikudepotserver.dataobjects.auto;

import org.apache.cayenne.exp.Property;
import org.haiku.haikudepotserver.dataobjects.support.AbstractDataObject;

/**
 * Class _Prominence was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Prominence extends AbstractDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<String> NAME = Property.create("name", String.class);
    public static final Property<Integer> ORDERING = Property.create("ordering", Integer.class);

    public String getName() {
        return (String)readProperty("name");
    }

    public Integer getOrdering() {
        return (Integer)readProperty("ordering");
    }

}
