package org.haiku.haikudepotserver.dataobjects.auto;

import java.util.Date;

import org.apache.cayenne.exp.Property;
import org.haiku.haikudepotserver.dataobjects.support.AbstractDataObject;

/**
 * Class _Response was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Response extends AbstractDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<Date> CREATE_TIMESTAMP = Property.create("createTimestamp", Date.class);
    public static final Property<String> RESPONSE = Property.create("response", String.class);
    public static final Property<String> TOKEN = Property.create("token", String.class);

    public void setCreateTimestamp(Date createTimestamp) {
        writeProperty("createTimestamp", createTimestamp);
    }
    public Date getCreateTimestamp() {
        return (Date)readProperty("createTimestamp");
    }

    public void setResponse(String response) {
        writeProperty("response", response);
    }
    public String getResponse() {
        return (String)readProperty("response");
    }

    public void setToken(String token) {
        writeProperty("token", token);
    }
    public String getToken() {
        return (String)readProperty("token");
    }

}
