package org.haiku.haikudepotserver.dataobjects.auto;

import org.apache.cayenne.exp.Property;
import org.haiku.haikudepotserver.dataobjects.support.AbstractDataObject;

/**
 * Class _UserUsageConditions was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _UserUsageConditions extends AbstractDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<String> CODE = Property.create("code", String.class);
    public static final Property<String> COPY_MARKDOWN = Property.create("copyMarkdown", String.class);
    public static final Property<Integer> MINIMUM_AGE = Property.create("minimumAge", Integer.class);
    public static final Property<Integer> ORDERING = Property.create("ordering", Integer.class);

    public void setCode(String code) {
        writeProperty("code", code);
    }
    public String getCode() {
        return (String)readProperty("code");
    }

    public void setCopyMarkdown(String copyMarkdown) {
        writeProperty("copyMarkdown", copyMarkdown);
    }
    public String getCopyMarkdown() {
        return (String)readProperty("copyMarkdown");
    }

    public void setMinimumAge(Integer minimumAge) {
        writeProperty("minimumAge", minimumAge);
    }
    public Integer getMinimumAge() {
        return (Integer)readProperty("minimumAge");
    }

    public void setOrdering(Integer ordering) {
        writeProperty("ordering", ordering);
    }
    public Integer getOrdering() {
        return (Integer)readProperty("ordering");
    }

}
