package org.haiku.haikudepotserver.dataobjects.auto;

import java.sql.Timestamp;

import org.apache.cayenne.exp.Property;
import org.haiku.haikudepotserver.dataobjects.User;
import org.haiku.haikudepotserver.dataobjects.UserUsageConditions;
import org.haiku.haikudepotserver.dataobjects.support.AbstractDataObject;

/**
 * Class _UserUsageConditionsAgreement was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _UserUsageConditionsAgreement extends AbstractDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<Boolean> ACTIVE = Property.create("active", Boolean.class);
    public static final Property<Timestamp> TIMESTAMP_AGREED = Property.create("timestampAgreed", Timestamp.class);
    public static final Property<User> USER = Property.create("user", User.class);
    public static final Property<UserUsageConditions> USER_USAGE_CONDITIONS = Property.create("userUsageConditions", UserUsageConditions.class);

    public void setActive(Boolean active) {
        writeProperty("active", active);
    }
    public Boolean getActive() {
        return (Boolean)readProperty("active");
    }

    public void setTimestampAgreed(Timestamp timestampAgreed) {
        writeProperty("timestampAgreed", timestampAgreed);
    }
    public Timestamp getTimestampAgreed() {
        return (Timestamp)readProperty("timestampAgreed");
    }

    public void setUser(User user) {
        setToOneTarget("user", user, true);
    }

    public User getUser() {
        return (User)readProperty("user");
    }


    public void setUserUsageConditions(UserUsageConditions userUsageConditions) {
        setToOneTarget("userUsageConditions", userUsageConditions, true);
    }

    public UserUsageConditions getUserUsageConditions() {
        return (UserUsageConditions)readProperty("userUsageConditions");
    }


    protected abstract void onPostAdd();

}
