package org.haiku.haikudepotserver.dataobjects.auto;

import java.util.Date;

import org.apache.cayenne.exp.Property;
import org.haiku.haikudepotserver.dataobjects.NaturalLanguage;
import org.haiku.haikudepotserver.dataobjects.PkgVersion;
import org.haiku.haikudepotserver.dataobjects.User;
import org.haiku.haikudepotserver.dataobjects.UserRatingStability;
import org.haiku.haikudepotserver.dataobjects.support.AbstractDataObject;

/**
 * Class _UserRating was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _UserRating extends AbstractDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<Boolean> ACTIVE = Property.create("active", Boolean.class);
    public static final Property<String> CODE = Property.create("code", String.class);
    public static final Property<String> COMMENT = Property.create("comment", String.class);
    public static final Property<Date> CREATE_TIMESTAMP = Property.create("createTimestamp", Date.class);
    public static final Property<Date> MODIFY_TIMESTAMP = Property.create("modifyTimestamp", Date.class);
    public static final Property<Short> RATING = Property.create("rating", Short.class);
    public static final Property<NaturalLanguage> NATURAL_LANGUAGE = Property.create("naturalLanguage", NaturalLanguage.class);
    public static final Property<PkgVersion> PKG_VERSION = Property.create("pkgVersion", PkgVersion.class);
    public static final Property<User> USER = Property.create("user", User.class);
    public static final Property<UserRatingStability> USER_RATING_STABILITY = Property.create("userRatingStability", UserRatingStability.class);

    public void setActive(Boolean active) {
        writeProperty("active", active);
    }
    public Boolean getActive() {
        return (Boolean)readProperty("active");
    }

    public void setCode(String code) {
        writeProperty("code", code);
    }
    public String getCode() {
        return (String)readProperty("code");
    }

    public void setComment(String comment) {
        writeProperty("comment", comment);
    }
    public String getComment() {
        return (String)readProperty("comment");
    }

    public void setCreateTimestamp(Date createTimestamp) {
        writeProperty("createTimestamp", createTimestamp);
    }
    public Date getCreateTimestamp() {
        return (Date)readProperty("createTimestamp");
    }

    public void setModifyTimestamp(Date modifyTimestamp) {
        writeProperty("modifyTimestamp", modifyTimestamp);
    }
    public Date getModifyTimestamp() {
        return (Date)readProperty("modifyTimestamp");
    }

    public void setRating(Short rating) {
        writeProperty("rating", rating);
    }
    public Short getRating() {
        return (Short)readProperty("rating");
    }

    public void setNaturalLanguage(NaturalLanguage naturalLanguage) {
        setToOneTarget("naturalLanguage", naturalLanguage, true);
    }

    public NaturalLanguage getNaturalLanguage() {
        return (NaturalLanguage)readProperty("naturalLanguage");
    }


    public void setPkgVersion(PkgVersion pkgVersion) {
        setToOneTarget("pkgVersion", pkgVersion, true);
    }

    public PkgVersion getPkgVersion() {
        return (PkgVersion)readProperty("pkgVersion");
    }


    public void setUser(User user) {
        setToOneTarget("user", user, true);
    }

    public User getUser() {
        return (User)readProperty("user");
    }


    public void setUserRatingStability(UserRatingStability userRatingStability) {
        setToOneTarget("userRatingStability", userRatingStability, true);
    }

    public UserRatingStability getUserRatingStability() {
        return (UserRatingStability)readProperty("userRatingStability");
    }


    protected abstract void onPostAdd();

}
