/*
 * Copyright 2013, Andrew Lindesay
 * Distributed under the terms of the MIT License.
 */

/**
 * <p>This directive renders a small block of HTML that represents the breadcrumbs.  The breadcrumbs are not actually
 * the path by which you arrived where you are, but a derived idea of where you are that is generated by the page's
 * controller that you are currently looking at.  Note that this directive will insert the 'home' breadcrumb item
 * itself so you need not keep supplying that.</p>
 */

angular.module('haikudepotserver').directive('breadcrumbs',function() {
    return {
        restrict: 'E',
        templateUrl:'/js/app/directive/breadcrumbs.html',
        replace: true,
        scope: {
            items: '='
        },
        controller:
            ['$scope','$location',
                function($scope,$location) {

                    $scope.derivedItems = undefined;

                    function isItemActive(item) {
                        if(!item) {
                            return false;
                        }
                        return item.path == $location.path();
                    }

                    function deriveItems() {
                        $scope.derivedItems = [{
                            title : 'Home',
                            path : '/'
                        }].concat($scope.items);
                    }

                    deriveItems();

                    $scope.shouldShowItems = function() {
                        return $scope.items;
                    }

                    $scope.$watch('items', function(newValue) {
                        deriveItems();
                    });

                    $scope.goItem = function(item) {
                        $location.path(item.path).search({});
                        return false;
                    }

                    $scope.isItemActive = function(item) {
                        return isItemActive(item);
                    }

                    $scope.listItemClass = function(item) {
                        if(isItemActive(item)) {
                            return [ 'active' ];
                        }

                        return [];
                    }

                }
            ]
    };
});