# =====================================
# Copyright 2024-2025, Andrew Lindesay
# Distributed under the terms of the MIT License.
# =====================================

FROM debian:12.11-slim AS base