# =====================================
# Copyright 2024-2025, Andrew Lindesay
# Distributed under the terms of the MIT License.
# =====================================

# -------------------------------------
# Create the container that will eventually run the graphics server

FROM java_maven_build AS java_maven_build_server_graphics

# perform the build of the application.
RUN ./mvnw clean
RUN ./mvnw install --also-make --projects haikudepotserver-server-graphics

FROM java_base AS runtime

# Build time env-vars
ENV X_HDS_OXIPNG_HOME=/opt/oxipng
ENV X_HDS_HVIF2PNG_HOME=/opt/hvif2png
ENV X_HDS_SERVER_GRAPHICS_APP_HOME="/opt/haikudepotserver-server-graphics"

# These are picked up by Spring Boot
ENV SERVER_PORT=8085
ENV MANAGEMENT_SERVER_PORT=8086
ENV HDS_TOOL_OXIPNG_PATH=${X_HDS_OXIPNG_HOME}/bin/oxipng
ENV HDS_TOOL_HVIF2PNG_PATH=${X_HDS_HVIF2PNG_HOME}/bin/hvif2png.sh

# The hvif2png tool requires the png library

RUN apt-get update && \
    apt-get -y install temurin-25-jre && \
    apt-get -y install libpng16-16 imagemagick optipng pngquant

RUN mkdir -p "${X_HDS_HVIF2PNG_HOME}/bin"
RUN mkdir -p "${X_HDS_HVIF2PNG_HOME}/lib"
COPY --from=hvif2png-build /generated.x86_64/objects/linux/x86_64/release/tools/hvif2png/hvif2png "${X_HDS_HVIF2PNG_HOME}/bin/hvif2png"
COPY support/graphics-services/hvif2png.sh "${X_HDS_HVIF2PNG_HOME}/bin/hvif2png.sh"
COPY --from=hvif2png-build /generated.x86_64/objects/linux/lib/libroot_build.so "${X_HDS_HVIF2PNG_HOME}/lib/libroot_build.so"
COPY --from=hvif2png-build /generated.x86_64/objects/linux/lib/libbe_build.so "${X_HDS_HVIF2PNG_HOME}/lib/libbe_build.so"

RUN mkdir -p "${X_HDS_OXIPNG_HOME}/bin"
COPY --from=oxipng-build "/opt/oxipng/bin/oxipng" "${HDS_TOOL_OXIPNG_PATH}"

RUN chmod +x "${HDS_TOOL_HVIF2PNG_PATH}"

COPY --from=java_maven_build_server_graphics /hds-src/haikudepotserver-server-graphics/target/haikudepotserver-server-graphics-*.jar \
    ${X_HDS_SERVER_GRAPHICS_APP_HOME}/app.jar

CMD [ "java", \
    "-Xms128m", \
    "-Xmx128m", \
    "-Dfile.encoding=UTF-8", \
    "-Duser.timezone=GMT0", \
    "-Djava.net.preferIPv4Stack=true", \
    "-Djava.awt.headless=true", \
    "-jar", \
    "/opt/haikudepotserver-server-graphics/app.jar" ]

HEALTHCHECK --interval=30s --timeout=10s CMD curl -f http://localhost:${MANAGEMENT_SERVER_PORT}/actuator/health
EXPOSE ${SEVER_PORT} ${MANAGEMENT_SERVER_PORT}