# =====================================
# Copyright 2024, Andrew Lindesay
# Distributed under the terms of the MIT License.
# =====================================

FROM java_maven_build AS java_maven_build_webapp

# perform the build of the application.
RUN ./mvnw clean
RUN ./mvnw install --also-make --projects haikudepotserver-webapp

FROM java_base AS runtime

RUN apt-get update && \
    apt-get -y install temurin-21-jre && \
    apt-get -y install curl fontconfig fonts-dejavu-core

ENV HDS_B_HTTP_PORT=8080
ENV HDS_B_HTTP_ACTUATOR_PORT=8081
ENV HDS_B_INSTALL_ROOT="/opt/haikudepotserver"
RUN mkdir ${HDS_B_INSTALL_ROOT}

COPY --from=java_maven_build_webapp /hds-src/haikudepotserver-core/target/classes/build.properties ${HDS_B_INSTALL_ROOT}
COPY --from=java_maven_build_webapp /hds-src/haikudepotserver-webapp/target/haikudepotserver-webapp-*.jar ${HDS_B_INSTALL_ROOT}/app.jar

COPY ./support/deployment/config.properties ${HDS_B_INSTALL_ROOT}

CMD \
    java \
    -Dfile.encoding=UTF-8 \
    -Duser.timezone=GMT0 \
    -Xms450m \
    -Xmx450m \
    -Djava.net.preferIPv4Stack=true \
    -Djava.awt.headless=true \
    -Dconfig.properties=file://${HDS_B_INSTALL_ROOT}/config.properties \
    -Dserver.port=${HDS_B_HTTP_PORT} \
    -Dmanagement.server.port=${HDS_B_HTTP_ACTUATOR_PORT} \
    -jar \
    ${HDS_B_INSTALL_ROOT}/app.jar

HEALTHCHECK --interval=30s --timeout=10s CMD curl -f http://localhost:${HDS_B_HTTP_ACTUATOR_PORT}/actuator/health
EXPOSE ${HDS_B_HTTP_PORT} ${HDS_B_HTTP_ACTUATOR_PORT}
