# =====================================
# Copyright 2024-2026, Andrew Lindesay
# Distributed under the terms of the MIT License.
# =====================================

# Build the hvif2png tooling

FROM base AS hvif2png-build

# 2026-03-29
ENV HAIKU_HASH=634373e466adb6f2045bf4d0ecf7bfe33c997ade
ENV BUILDTOOLS_HASH=d8207e22d27163c154d98aed3688926809da901c

RUN apt-get update && \
    apt-get -y install git nasm bc autoconf automake texinfo flex bison gawk build-essential unzip wget \
        zip less zlib1g-dev libzstd-dev xorriso libtool gcc-multilib python3 libpng16-16 libpng-dev

ADD "https://github.com/haiku/buildtools/archive/${BUILDTOOLS_HASH}.tar.gz" /buildtools.tgz
ADD "https://github.com/haiku/haiku/archive/${HAIKU_HASH}.tar.gz" /haiku.tgz

RUN tar -xzf ./buildtools.tgz
RUN tar -xzf ./haiku.tgz

RUN mv buildtools-${BUILDTOOLS_HASH} buildtools
RUN mv haiku-${HAIKU_HASH} haiku

WORKDIR "/buildtools/jam"
RUN make && ./jam0 install

RUN mkdir "/generated.x86_64"
WORKDIR "/generated.x86_64"
RUN ../haiku/configure --host-only

RUN apt-get -y install libpng-dev

RUN HAIKU_REVISION=123 jam -q "<build>hvif2png"