# =====================================
# Copyright 2024-2026, Andrew Lindesay
# Distributed under the terms of the MIT License.
# =====================================

# Build the hvif2png tooling

FROM base AS hvif2png-build

# 2025-10-17
ENV HAIKU_HASH=f357ddbe8e4a96026cfc1a27fed5e75ef1af0837
ENV BUILDTOOLS_HASH=13c7a4265a1024903b120f3bf11cd89ff9f4477a

RUN apt-get update && \
    apt-get -y install git nasm bc autoconf automake texinfo flex bison gawk build-essential unzip wget \
        zip less zlib1g-dev libzstd-dev xorriso libtool gcc-multilib python3 libpng16-16 libpng-dev

ADD "https://github.com/haiku/buildtools/archive/${BUILDTOOLS_HASH}.tar.gz" /buildtools.tgz
ADD "https://github.com/haiku/haiku/archive/${HAIKU_HASH}.tar.gz" /haiku.tgz

RUN tar -xzf ./buildtools.tgz
RUN tar -xzf ./haiku.tgz

RUN mv buildtools-${BUILDTOOLS_HASH} buildtools
RUN mv haiku-${HAIKU_HASH} haiku

WORKDIR "/buildtools/jam"
RUN make && ./jam0 install

RUN mkdir "/generated.x86_64"
WORKDIR "/generated.x86_64"
RUN ../haiku/configure --host-only

RUN apt-get -y install libpng-dev

RUN HAIKU_REVISION=123 jam -q "<build>hvif2png"