# =====================================
# Copyright 2024-2025, Andrew Lindesay
# Distributed under the terms of the MIT License.
# =====================================

FROM java_maven_build AS java_maven_build_webapp

# perform the build of the application.
RUN ./mvnw clean
RUN ./mvnw install --also-make --projects haikudepotserver-webapp

FROM java_base AS runtime

RUN apt-get update && \
    apt-get -y install temurin-25-jre && \
    apt-get -y install curl fontconfig fonts-dejavu-core

# These will be picked up by Spring Boot as a property
ENV SERVER_PORT=8080
ENV MANGEMENT_SERVER_PORT=8081

# These are really specific to this build script
ENV X_HDS_B_INSTALL_ROOT="/opt/haikudepotserver"
RUN mkdir ${X_HDS_B_INSTALL_ROOT}

COPY --from=java_maven_build_webapp /hds-src/haikudepotserver-core/target/classes/build.properties ${X_HDS_B_INSTALL_ROOT}
COPY --from=java_maven_build_webapp /hds-src/haikudepotserver-webapp/target/haikudepotserver-webapp-*.jar ${X_HDS_B_INSTALL_ROOT}/app.jar

CMD [ "java", \
    "-Xms450m", \
    "-Xmx450m", \
    "-Dfile.encoding=UTF-8", \
    "-Duser.timezone=GMT0", \
    "-Djava.net.preferIPv4Stack=true", \
    "-Djava.awt.headless=true", \
    "-jar", \
    "/opt/haikudepotserver/app.jar" ]

HEALTHCHECK --interval=30s --timeout=10s CMD curl -f http://localhost:${MANGEMENT_SERVER_PORT}/actuator/health
EXPOSE ${SERVER_PORT} ${MANGEMENT_SERVER_PORT}
