# =====================================
# Copyright 2022-2026, Andrew Lindesay
# Distributed under the terms of the MIT License.
# =====================================

# -------------------------------------
# Base image with the Eclipse Temurin repository setup.

FROM base AS java_base

RUN apt-get update && \
    apt-get -y install wget apt-transport-https gnupg locales

RUN mkdir /adoptium

RUN wget -O - "https://packages.adoptium.net/artifactory/api/gpg/key/public" | gpg --dearmour | dd of=/adoptium/apt-keyring.gpg
COPY support/deployment/deb-adoptium-sources-template.txt /adoptium/deb-adoptium-sources-template.txt
RUN OS_VERSION_CODENAME="$(awk -F= '/^VERSION_CODENAME/{print$2}' /etc/os-release)" && \
    cat /adoptium/deb-adoptium-sources-template.txt | sed -e "s/SUITE/${OS_VERSION_CODENAME}/g" | dd of=/etc/apt/sources.list.d/adoptium.sources

ENV LANG='en_US.UTF-8' LANGUAGE='en_US:en' LC_ALL='en_US.UTF-8'

# -------------------------------------
# Assemble the build image with the dependencies

FROM java_base AS java_maven_build

RUN apt-get update && \
    apt-get -y install temurin-25-jdk && \
    apt-get -y install wget python3 fontconfig fonts-dejavu-core lsb-release gnupg2 && \
    apt-get -y install postgresql postgresql-contrib

# copy the source into the build machine
RUN mkdir /hds-src

COPY ./mvnw /hds-src/mvnw
COPY ./.mvn/wrapper/maven-wrapper.properties /hds-src/.mvn/wrapper/maven-wrapper.properties

COPY ./pom.xml /hds-src/pom.xml
COPY ./haikudepotserver-parent/pom.xml /hds-src/haikudepotserver-parent/pom.xml
COPY ./haikudepotserver-driversettings/pom.xml /hds-src/haikudepotserver-driversettings/pom.xml
COPY ./haikudepotserver-core-test/pom.xml /hds-src/haikudepotserver-core-test/pom.xml
COPY ./haikudepotserver-api1/pom.xml /hds-src/haikudepotserver-api1/pom.xml
COPY ./haikudepotserver-api2/pom.xml /hds-src/haikudepotserver-api2/pom.xml
COPY ./haikudepotserver-packagefile/pom.xml /hds-src/haikudepotserver-packagefile/pom.xml
COPY ./haikudepotserver-packagetools/pom.xml /hds-src/haikudepotserver-packagetools/pom.xml
COPY ./haikudepotserver-server-graphics/pom.xml /hds-src/haikudepotserver-server-graphics/pom.xml
COPY ./haikudepotserver-spa1/pom.xml /hds-src/haikudepotserver-spa1/pom.xml
COPY ./haikudepotserver-webapp/pom.xml /hds-src/haikudepotserver-webapp/pom.xml
COPY ./haikudepotserver-core/pom.xml /hds-src/haikudepotserver-core/pom.xml

WORKDIR /hds-src

RUN ./mvnw clean org.apache.maven.plugins:maven-dependency-plugin:3.9.0:go-offline

COPY ./haikudepotserver-spa1/package.json /hds-src/haikudepotserver-spa1/package.json

# capture the NodeJS dependencies into the image
RUN ./mvnw -f haikudepotserver-spa1 com.github.eirslett:frontend-maven-plugin:install-node-and-npm
RUN ./mvnw -f haikudepotserver-spa1 com.github.eirslett:frontend-maven-plugin:npm -Pfrontend.npm.arguments=ci

# copy the rest of the source
COPY ./haikudepotserver-parent /hds-src/haikudepotserver-parent
COPY ./haikudepotserver-driversettings /hds-src/haikudepotserver-driversettings
COPY ./haikudepotserver-core-test /hds-src/haikudepotserver-core-test
COPY ./haikudepotserver-api2 /hds-src/haikudepotserver-api2
COPY ./haikudepotserver-packagefile /hds-src/haikudepotserver-packagefile
COPY ./haikudepotserver-packagetools /hds-src/haikudepotserver-packagetools
COPY ./haikudepotserver-webapp /hds-src/haikudepotserver-webapp
COPY ./haikudepotserver-server-graphics /hds-src/haikudepotserver-server-graphics
COPY ./haikudepotserver-spa1 /hds-src/haikudepotserver-spa1
COPY ./haikudepotserver-api1 /hds-src/haikudepotserver-api1
COPY ./haikudepotserver-core /hds-src/haikudepotserver-core

# Just to be sure for local builds
# TODO; find a better way to do this.
RUN rm -f /hds-src/haikudepotserver-webapp/src/main/resources/local.properties

# This will cause the integration tests to be run against a child process
# of maven.
ENV TEST_DATABASE_TYPE="START_LOCAL_DATABASE"

# The build is now performed for the projects that are required
# in the respective "last-mile" build phase.