package org.haiku.haikudepotserver.dataobjects.auto;

import java.util.Date;
import java.util.List;

import org.haiku.haikudepotserver.dataobjects.Pkg;
import org.haiku.haikudepotserver.dataobjects.PkgScreenshotImage;
import org.haiku.haikudepotserver.dataobjects.support.AbstractDataObject;

/**
 * Class _PkgScreenshot was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _PkgScreenshot extends AbstractDataObject {

    public static final String CODE_PROPERTY = "code";
    public static final String CREATE_TIMESTAMP_PROPERTY = "createTimestamp";
    public static final String HEIGHT_PROPERTY = "height";
    public static final String LENGTH_PROPERTY = "length";
    public static final String MODIFY_TIMESTAMP_PROPERTY = "modifyTimestamp";
    public static final String ORDERING_PROPERTY = "ordering";
    public static final String WIDTH_PROPERTY = "width";
    public static final String PKG_PROPERTY = "pkg";
    public static final String PKG_SCREENSHOT_IMAGES_PROPERTY = "pkgScreenshotImages";

    public static final String ID_PK_COLUMN = "id";

    public void setCode(String code) {
        writeProperty(CODE_PROPERTY, code);
    }
    public String getCode() {
        return (String)readProperty(CODE_PROPERTY);
    }

    public void setCreateTimestamp(Date createTimestamp) {
        writeProperty(CREATE_TIMESTAMP_PROPERTY, createTimestamp);
    }
    public Date getCreateTimestamp() {
        return (Date)readProperty(CREATE_TIMESTAMP_PROPERTY);
    }

    public void setHeight(Integer height) {
        writeProperty(HEIGHT_PROPERTY, height);
    }
    public Integer getHeight() {
        return (Integer)readProperty(HEIGHT_PROPERTY);
    }

    public void setLength(Integer length) {
        writeProperty(LENGTH_PROPERTY, length);
    }
    public Integer getLength() {
        return (Integer)readProperty(LENGTH_PROPERTY);
    }

    public void setModifyTimestamp(Date modifyTimestamp) {
        writeProperty(MODIFY_TIMESTAMP_PROPERTY, modifyTimestamp);
    }
    public Date getModifyTimestamp() {
        return (Date)readProperty(MODIFY_TIMESTAMP_PROPERTY);
    }

    public void setOrdering(Integer ordering) {
        writeProperty(ORDERING_PROPERTY, ordering);
    }
    public Integer getOrdering() {
        return (Integer)readProperty(ORDERING_PROPERTY);
    }

    public void setWidth(Integer width) {
        writeProperty(WIDTH_PROPERTY, width);
    }
    public Integer getWidth() {
        return (Integer)readProperty(WIDTH_PROPERTY);
    }

    public void setPkg(Pkg pkg) {
        setToOneTarget(PKG_PROPERTY, pkg, true);
    }

    public Pkg getPkg() {
        return (Pkg)readProperty(PKG_PROPERTY);
    }


    public void addToPkgScreenshotImages(PkgScreenshotImage obj) {
        addToManyTarget(PKG_SCREENSHOT_IMAGES_PROPERTY, obj, true);
    }
    public void removeFromPkgScreenshotImages(PkgScreenshotImage obj) {
        removeToManyTarget(PKG_SCREENSHOT_IMAGES_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<PkgScreenshotImage> getPkgScreenshotImages() {
        return (List<PkgScreenshotImage>)readProperty(PKG_SCREENSHOT_IMAGES_PROPERTY);
    }


}
