package org.haiku.haikudepotserver.dataobjects.auto;

import java.util.List;

import org.haiku.haikudepotserver.dataobjects.MediaType;
import org.haiku.haikudepotserver.dataobjects.Pkg;
import org.haiku.haikudepotserver.dataobjects.PkgIconImage;
import org.haiku.haikudepotserver.dataobjects.support.AbstractDataObject;

/**
 * Class _PkgIcon was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _PkgIcon extends AbstractDataObject {

    public static final String SIZE_PROPERTY = "size";
    public static final String MEDIA_TYPE_PROPERTY = "mediaType";
    public static final String PKG_PROPERTY = "pkg";
    public static final String PKG_ICON_IMAGES_PROPERTY = "pkgIconImages";

    public static final String ID_PK_COLUMN = "id";

    public void setSize(Integer size) {
        writeProperty(SIZE_PROPERTY, size);
    }
    public Integer getSize() {
        return (Integer)readProperty(SIZE_PROPERTY);
    }

    public void setMediaType(MediaType mediaType) {
        setToOneTarget(MEDIA_TYPE_PROPERTY, mediaType, true);
    }

    public MediaType getMediaType() {
        return (MediaType)readProperty(MEDIA_TYPE_PROPERTY);
    }


    public void setPkg(Pkg pkg) {
        setToOneTarget(PKG_PROPERTY, pkg, true);
    }

    public Pkg getPkg() {
        return (Pkg)readProperty(PKG_PROPERTY);
    }


    public void addToPkgIconImages(PkgIconImage obj) {
        addToManyTarget(PKG_ICON_IMAGES_PROPERTY, obj, true);
    }
    public void removeFromPkgIconImages(PkgIconImage obj) {
        removeToManyTarget(PKG_ICON_IMAGES_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<PkgIconImage> getPkgIconImages() {
        return (List<PkgIconImage>)readProperty(PKG_ICON_IMAGES_PROPERTY);
    }


}
