package org.haiku.haikudepotserver.dataobjects.auto;

import org.haiku.haikudepotserver.dataobjects.support.AbstractDataObject;

/**
 * Class _Prominence was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Prominence extends AbstractDataObject {

    public static final String NAME_PROPERTY = "name";
    public static final String ORDERING_PROPERTY = "ordering";

    public static final String ID_PK_COLUMN = "id";

    public String getName() {
        return (String)readProperty(NAME_PROPERTY);
    }

    public Integer getOrdering() {
        return (Integer)readProperty(ORDERING_PROPERTY);
    }

}
