package org.haikuos.haikudepotserver.dataobjects.auto;

import org.haikuos.haikudepotserver.dataobjects.Permission;
import org.haikuos.haikudepotserver.dataobjects.Repository;
import org.haikuos.haikudepotserver.dataobjects.support.AbstractDataObject;

/**
 * Class _PermissionPublicRepository was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _PermissionPublicRepository extends AbstractDataObject {

    public static final String REQUIRES_USER_PROPERTY = "requiresUser";
    public static final String PERMISSION_PROPERTY = "permission";
    public static final String REPOSITORY_PROPERTY = "repository";

    public static final String ID_PK_COLUMN = "id";

    public void setRequiresUser(Boolean requiresUser) {
        writeProperty(REQUIRES_USER_PROPERTY, requiresUser);
    }
    public Boolean getRequiresUser() {
        return (Boolean)readProperty(REQUIRES_USER_PROPERTY);
    }

    public void setPermission(Permission permission) {
        setToOneTarget(PERMISSION_PROPERTY, permission, true);
    }

    public Permission getPermission() {
        return (Permission)readProperty(PERMISSION_PROPERTY);
    }


    public void setRepository(Repository repository) {
        setToOneTarget(REPOSITORY_PROPERTY, repository, true);
    }

    public Repository getRepository() {
        return (Repository)readProperty(REPOSITORY_PROPERTY);
    }


}
