package org.haikuos.haikudepotserver.dataobjects.auto;

import org.haikuos.haikudepotserver.dataobjects.Permission;
import org.haikuos.haikudepotserver.dataobjects.Repository;
import org.haikuos.haikudepotserver.dataobjects.User;
import org.haikuos.haikudepotserver.dataobjects.support.AbstractDataObject;

/**
 * Class _PermissionUserRepository was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _PermissionUserRepository extends AbstractDataObject {

    public static final String PERMISSION_PROPERTY = "permission";
    public static final String REPOSITORY_PROPERTY = "repository";
    public static final String USER_PROPERTY = "user";

    public static final String ID_PK_COLUMN = "id";

    public void setPermission(Permission permission) {
        setToOneTarget(PERMISSION_PROPERTY, permission, true);
    }

    public Permission getPermission() {
        return (Permission)readProperty(PERMISSION_PROPERTY);
    }


    public void setRepository(Repository repository) {
        setToOneTarget(REPOSITORY_PROPERTY, repository, true);
    }

    public Repository getRepository() {
        return (Repository)readProperty(REPOSITORY_PROPERTY);
    }


    public void setUser(User user) {
        setToOneTarget(USER_PROPERTY, user, true);
    }

    public User getUser() {
        return (User)readProperty(USER_PROPERTY);
    }


}
