package org.haikuos.haikudepotserver.dataobjects.auto;

import org.haikuos.haikudepotserver.dataobjects.Pkg;
import org.haikuos.haikudepotserver.dataobjects.PkgCategory;
import org.haikuos.haikudepotserver.dataobjects.support.AbstractDataObject;

/**
 * Class _PkgPkgCategory was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _PkgPkgCategory extends AbstractDataObject {

    public static final String PKG_PROPERTY = "pkg";
    public static final String PKG_CATEGORY_PROPERTY = "pkgCategory";

    public static final String ID_PK_COLUMN = "id";

    public void setPkg(Pkg pkg) {
        setToOneTarget(PKG_PROPERTY, pkg, true);
    }

    public Pkg getPkg() {
        return (Pkg)readProperty(PKG_PROPERTY);
    }


    public void setPkgCategory(PkgCategory pkgCategory) {
        setToOneTarget(PKG_CATEGORY_PROPERTY, pkgCategory, true);
    }

    public PkgCategory getPkgCategory() {
        return (PkgCategory)readProperty(PKG_CATEGORY_PROPERTY);
    }


}
