package org.haikuos.haikudepotserver.dataobjects.auto;

import java.util.Date;

import org.haikuos.haikudepotserver.dataobjects.LocalizationContent;
import org.haikuos.haikudepotserver.dataobjects.NaturalLanguage;
import org.haikuos.haikudepotserver.dataobjects.PkgVersion;
import org.haikuos.haikudepotserver.dataobjects.support.AbstractDataObject;

/**
 * Class _PkgVersionLocalization was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _PkgVersionLocalization extends AbstractDataObject {

    public static final String CREATE_TIMESTAMP_PROPERTY = "createTimestamp";
    public static final String MODIFY_TIMESTAMP_PROPERTY = "modifyTimestamp";
    public static final String DESCRIPTION_LOCALIZATION_CONTENT_PROPERTY = "descriptionLocalizationContent";
    public static final String NATURAL_LANGUAGE_PROPERTY = "naturalLanguage";
    public static final String PKG_VERSION_PROPERTY = "pkgVersion";
    public static final String SUMMARY_LOCALIZATION_CONTENT_PROPERTY = "summaryLocalizationContent";
    public static final String TITLE_LOCALIZATION_CONTENT_PROPERTY = "titleLocalizationContent";

    public static final String ID_PK_COLUMN = "id";

    public void setCreateTimestamp(Date createTimestamp) {
        writeProperty(CREATE_TIMESTAMP_PROPERTY, createTimestamp);
    }
    public Date getCreateTimestamp() {
        return (Date)readProperty(CREATE_TIMESTAMP_PROPERTY);
    }

    public void setModifyTimestamp(Date modifyTimestamp) {
        writeProperty(MODIFY_TIMESTAMP_PROPERTY, modifyTimestamp);
    }
    public Date getModifyTimestamp() {
        return (Date)readProperty(MODIFY_TIMESTAMP_PROPERTY);
    }

    public void setDescriptionLocalizationContent(LocalizationContent descriptionLocalizationContent) {
        setToOneTarget(DESCRIPTION_LOCALIZATION_CONTENT_PROPERTY, descriptionLocalizationContent, true);
    }

    public LocalizationContent getDescriptionLocalizationContent() {
        return (LocalizationContent)readProperty(DESCRIPTION_LOCALIZATION_CONTENT_PROPERTY);
    }


    public void setNaturalLanguage(NaturalLanguage naturalLanguage) {
        setToOneTarget(NATURAL_LANGUAGE_PROPERTY, naturalLanguage, true);
    }

    public NaturalLanguage getNaturalLanguage() {
        return (NaturalLanguage)readProperty(NATURAL_LANGUAGE_PROPERTY);
    }


    public void setPkgVersion(PkgVersion pkgVersion) {
        setToOneTarget(PKG_VERSION_PROPERTY, pkgVersion, true);
    }

    public PkgVersion getPkgVersion() {
        return (PkgVersion)readProperty(PKG_VERSION_PROPERTY);
    }


    public void setSummaryLocalizationContent(LocalizationContent summaryLocalizationContent) {
        setToOneTarget(SUMMARY_LOCALIZATION_CONTENT_PROPERTY, summaryLocalizationContent, true);
    }

    public LocalizationContent getSummaryLocalizationContent() {
        return (LocalizationContent)readProperty(SUMMARY_LOCALIZATION_CONTENT_PROPERTY);
    }


    public void setTitleLocalizationContent(LocalizationContent titleLocalizationContent) {
        setToOneTarget(TITLE_LOCALIZATION_CONTENT_PROPERTY, titleLocalizationContent, true);
    }

    public LocalizationContent getTitleLocalizationContent() {
        return (LocalizationContent)readProperty(TITLE_LOCALIZATION_CONTENT_PROPERTY);
    }


}
