package org.haikuos.haikudepotserver.dataobjects.auto;

import org.haikuos.haikudepotserver.dataobjects.PkgIcon;
import org.haikuos.haikudepotserver.dataobjects.support.AbstractDataObject;

/**
 * Class _PkgIconImage was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _PkgIconImage extends AbstractDataObject {

    public static final String DATA_PROPERTY = "data";
    public static final String PKG_ICON_PROPERTY = "pkgIcon";

    public static final String ID_PK_COLUMN = "id";

    public void setData(byte[] data) {
        writeProperty(DATA_PROPERTY, data);
    }
    public byte[] getData() {
        return (byte[])readProperty(DATA_PROPERTY);
    }

    public void setPkgIcon(PkgIcon pkgIcon) {
        setToOneTarget(PKG_ICON_PROPERTY, pkgIcon, true);
    }

    public PkgIcon getPkgIcon() {
        return (PkgIcon)readProperty(PKG_ICON_PROPERTY);
    }


}
