package org.haikuos.haikudepotserver.dataobjects.auto;

import org.haikuos.haikudepotserver.dataobjects.Pkg;
import org.haikuos.haikudepotserver.dataobjects.Repository;
import org.haikuos.haikudepotserver.dataobjects.support.AbstractDataObject;

/**
 * Class _PkgUserRatingAggregate was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _PkgUserRatingAggregate extends AbstractDataObject {

    public static final String DERIVED_RATING_PROPERTY = "derivedRating";
    public static final String DERIVED_RATING_SAMPLE_SIZE_PROPERTY = "derivedRatingSampleSize";
    public static final String PKG_PROPERTY = "pkg";
    public static final String REPOSITORY_PROPERTY = "repository";

    public static final String ID_PK_COLUMN = "id";

    public void setDerivedRating(Float derivedRating) {
        writeProperty(DERIVED_RATING_PROPERTY, derivedRating);
    }
    public Float getDerivedRating() {
        return (Float)readProperty(DERIVED_RATING_PROPERTY);
    }

    public void setDerivedRatingSampleSize(Integer derivedRatingSampleSize) {
        writeProperty(DERIVED_RATING_SAMPLE_SIZE_PROPERTY, derivedRatingSampleSize);
    }
    public Integer getDerivedRatingSampleSize() {
        return (Integer)readProperty(DERIVED_RATING_SAMPLE_SIZE_PROPERTY);
    }

    public void setPkg(Pkg pkg) {
        setToOneTarget(PKG_PROPERTY, pkg, true);
    }

    public Pkg getPkg() {
        return (Pkg)readProperty(PKG_PROPERTY);
    }


    public void setRepository(Repository repository) {
        setToOneTarget(REPOSITORY_PROPERTY, repository, true);
    }

    public Repository getRepository() {
        return (Repository)readProperty(REPOSITORY_PROPERTY);
    }


}
