package org.haikuos.haikudepotserver.dataobjects.auto;

import org.haikuos.haikudepotserver.dataobjects.MediaType;
import org.haikuos.haikudepotserver.dataobjects.PkgScreenshot;
import org.haikuos.haikudepotserver.dataobjects.support.AbstractDataObject;

/**
 * Class _PkgScreenshotImage was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _PkgScreenshotImage extends AbstractDataObject {

    public static final String DATA_PROPERTY = "data";
    public static final String MEDIA_TYPE_PROPERTY = "mediaType";
    public static final String PKG_SCREENSHOT_PROPERTY = "pkgScreenshot";

    public static final String ID_PK_COLUMN = "id";

    public void setData(byte[] data) {
        writeProperty(DATA_PROPERTY, data);
    }
    public byte[] getData() {
        return (byte[])readProperty(DATA_PROPERTY);
    }

    public void setMediaType(MediaType mediaType) {
        setToOneTarget(MEDIA_TYPE_PROPERTY, mediaType, true);
    }

    public MediaType getMediaType() {
        return (MediaType)readProperty(MEDIA_TYPE_PROPERTY);
    }


    public void setPkgScreenshot(PkgScreenshot pkgScreenshot) {
        setToOneTarget(PKG_SCREENSHOT_PROPERTY, pkgScreenshot, true);
    }

    public PkgScreenshot getPkgScreenshot() {
        return (PkgScreenshot)readProperty(PKG_SCREENSHOT_PROPERTY);
    }


}
