package org.haikuos.haikudepotserver.dataobjects.auto;

import org.haikuos.haikudepotserver.dataobjects.PkgVersion;
import org.haikuos.haikudepotserver.dataobjects.support.AbstractDataObject;

/**
 * Class _PkgVersionCopyright was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _PkgVersionCopyright extends AbstractDataObject {

    public static final String BODY_PROPERTY = "body";
    public static final String PKG_VERSION_PROPERTY = "pkgVersion";

    public static final String ID_PK_COLUMN = "id";

    public void setBody(String body) {
        writeProperty(BODY_PROPERTY, body);
    }
    public String getBody() {
        return (String)readProperty(BODY_PROPERTY);
    }

    public void setPkgVersion(PkgVersion pkgVersion) {
        setToOneTarget(PKG_VERSION_PROPERTY, pkgVersion, true);
    }

    public PkgVersion getPkgVersion() {
        return (PkgVersion)readProperty(PKG_VERSION_PROPERTY);
    }


}
