package org.haikuos.haikudepotserver.dataobjects.auto;

import java.util.Date;
import java.util.List;

import org.haikuos.haikudepotserver.dataobjects.RepositorySource;
import org.haikuos.haikudepotserver.dataobjects.support.AbstractDataObject;

/**
 * Class _Repository was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Repository extends AbstractDataObject {

    public static final String ACTIVE_PROPERTY = "active";
    public static final String CODE_PROPERTY = "code";
    public static final String CREATE_TIMESTAMP_PROPERTY = "createTimestamp";
    public static final String DESCRIPTION_PROPERTY = "description";
    public static final String INFORMATION_URL_PROPERTY = "informationUrl";
    public static final String MODIFY_TIMESTAMP_PROPERTY = "modifyTimestamp";
    public static final String NAME_PROPERTY = "name";
    public static final String REPOSITORY_SOURCES_PROPERTY = "repositorySources";

    public static final String ID_PK_COLUMN = "id";

    public void setActive(Boolean active) {
        writeProperty(ACTIVE_PROPERTY, active);
    }
    public Boolean getActive() {
        return (Boolean)readProperty(ACTIVE_PROPERTY);
    }

    public void setCode(String code) {
        writeProperty(CODE_PROPERTY, code);
    }
    public String getCode() {
        return (String)readProperty(CODE_PROPERTY);
    }

    public void setCreateTimestamp(Date createTimestamp) {
        writeProperty(CREATE_TIMESTAMP_PROPERTY, createTimestamp);
    }
    public Date getCreateTimestamp() {
        return (Date)readProperty(CREATE_TIMESTAMP_PROPERTY);
    }

    public void setDescription(String description) {
        writeProperty(DESCRIPTION_PROPERTY, description);
    }
    public String getDescription() {
        return (String)readProperty(DESCRIPTION_PROPERTY);
    }

    public void setInformationUrl(String informationUrl) {
        writeProperty(INFORMATION_URL_PROPERTY, informationUrl);
    }
    public String getInformationUrl() {
        return (String)readProperty(INFORMATION_URL_PROPERTY);
    }

    public void setModifyTimestamp(Date modifyTimestamp) {
        writeProperty(MODIFY_TIMESTAMP_PROPERTY, modifyTimestamp);
    }
    public Date getModifyTimestamp() {
        return (Date)readProperty(MODIFY_TIMESTAMP_PROPERTY);
    }

    public void setName(String name) {
        writeProperty(NAME_PROPERTY, name);
    }
    public String getName() {
        return (String)readProperty(NAME_PROPERTY);
    }

    public void addToRepositorySources(RepositorySource obj) {
        addToManyTarget(REPOSITORY_SOURCES_PROPERTY, obj, true);
    }
    public void removeFromRepositorySources(RepositorySource obj) {
        removeToManyTarget(REPOSITORY_SOURCES_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<RepositorySource> getRepositorySources() {
        return (List<RepositorySource>)readProperty(REPOSITORY_SOURCES_PROPERTY);
    }


}
