apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: haikudepotserver-pg-volume-claim
  labels:
    app: postgres-pg
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi