apiVersion: apps/v1
kind: Deployment
metadata:
  name: haikudepotserver-webapp
  labels:
    app: haikudepotserver-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: haikudepotserver-webapp
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: haikudepotserver-webapp
    spec:
      containers:
        - name: haikudepotserver-webapp
          image: ghcr.io/haiku/haikudepotserver:1.0.177
          env:
            # Don't test the SMTP server to see if the POD is healthy.
            - name: MANAGEMENT_HEALTH_MAIL_ENABLED
              value: "false"
            - name: SPRING_MAIL_HOST
              value: "smtp"
              # This is the base URL used to formulate URLs to be sent out
              # that can be used to return back to the system.
              # For example; this might be used to create the URL used to
              # manage the password reset process.  The URL base is included
              # in the email body to users who have requested a password-reset.
              # This has to be configured because the application itself does
              # not know the path by which the HTTP request had reached it.
              #
              # In the case of a development environment, this base URL might
              # be something like "http://localhost:8080".
              #
              # Note that this value should have no trailing slash.
            - name: HDS_BASE_URL
              value: "http://localhost:30080"
            - name: HDS_AUTHENTICATION_JWS_ISSUER
              value: "dev.hds"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://haikudepotserver-pg-svc:5432/haikudepotserver"
            - name: SPRING_DATASOURCE_USERNAME
              value: haikudepotserver
            - name: SPRING_DATASOURCE_PASSWORD
              value: haikudepotserver
            - name: HDS_GRAPHICS_SERVER_BASE_URI
              value: http://haikudepotserver-server-graphics-svc:8085
            - name: HDS_REPOSITORY_IMPORT_ALLOWED_PKG_NAME_PATTERN
              value: "^.[Aa].+$"
          resources:
            limits:
              cpu: "1.0"
              memory: "2Gi"
            requests:
              cpu: "0.50"
              memory: "512Mi"
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 60
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 30
            failureThreshold: 2
---
apiVersion: v1
kind: Service
metadata:
  name: haikudepotserver-webapp-svc
spec:
  selector:
    app: haikudepotserver-webapp
  type: NodePort
  ports:
    - name: www
      port: 8080
      targetPort: 8080
      nodePort: 30080
    - name: actuator
      port: 8081
      targetPort: 8081
      nodePort: 30081