-- ------------------------------------------------------
-- SETUP
-- ------------------------------------------------------

-- Flyway will take care of this.
-- CREATE SCHEMA haikudepot;

-- ------------------------------------------------------
-- TABLES GENERATED BY CAYENNE MODELLER
-- ------------------------------------------------------

CREATE TABLE haikudepot.pkg_url_type (code VARCHAR(255) NOT NULL, id BIGINT NOT NULL, PRIMARY KEY (id));
CREATE TABLE haikudepot.publisher (active BOOLEAN NOT NULL, code VARCHAR(255) NULL, create_timestamp TIMESTAMP NOT NULL, email VARCHAR(1024) NULL, id BIGINT NOT NULL, modify_timestamp TIMESTAMP NOT NULL, name VARCHAR(1024) NOT NULL, site_url VARCHAR(1024) NULL, PRIMARY KEY (id));
CREATE TABLE haikudepot.architecture (code VARCHAR(255) NOT NULL, id BIGINT NOT NULL, PRIMARY KEY (id));
CREATE TABLE haikudepot.pkg (active BOOLEAN NOT NULL, create_timestamp TIMESTAMP NOT NULL, id BIGINT NOT NULL, modify_timestamp TIMESTAMP NOT NULL, name VARCHAR(255) NOT NULL, publisher_id BIGINT NULL, PRIMARY KEY (id));
CREATE TABLE haikudepot.repository (active BOOLEAN NOT NULL, architecture_id BIGINT NOT NULL, code VARCHAR(255) NOT NULL, create_timestamp TIMESTAMP NOT NULL, id BIGINT NOT NULL, modify_timestamp TIMESTAMP NOT NULL, url VARCHAR(1024) NOT NULL, PRIMARY KEY (id));
CREATE TABLE haikudepot.pkg_version (active BOOLEAN NOT NULL, architecture_id BIGINT NOT NULL, create_timestamp TIMESTAMP NOT NULL, id BIGINT NOT NULL, major VARCHAR(255) NOT NULL, micro VARCHAR(255) NULL, minor VARCHAR(255) NULL, modify_timestamp TIMESTAMP NOT NULL, pkg_id BIGINT NOT NULL, pre_release VARCHAR(255) NULL, repository_id BIGINT NOT NULL, revision INTEGER NULL, PRIMARY KEY (id));
CREATE TABLE haikudepot.pkg_version_copyright (body VARCHAR(4096) NOT NULL, id BIGINT NOT NULL, pkg_version_id BIGINT NOT NULL, PRIMARY KEY (id));
CREATE TABLE haikudepot.pkg_version_localization (description VARCHAR(8192) NULL, id BIGINT NOT NULL, pkg_version_id BIGINT NULL, summary VARCHAR(8192) NULL, PRIMARY KEY (id));
CREATE TABLE haikudepot.pkg_version_license (body VARCHAR(4096) NOT NULL, id BIGINT NOT NULL, pkg_version_id BIGINT NOT NULL, PRIMARY KEY (id));
CREATE TABLE haikudepot.pkg_version_url (id BIGINT NOT NULL, pkg_url_type_id BIGINT NOT NULL, pkg_version_id BIGINT NOT NULL, url VARCHAR(1024) NOT NULL, PRIMARY KEY (id));
CREATE TABLE haikudepot.user (active BOOLEAN NOT NULL, can_manage_users BOOLEAN NOT NULL, id BIGINT NOT NULL, is_root BOOLEAN NOT NULL, nickname VARCHAR(32) NOT NULL, password_hash VARCHAR(255) NOT NULL, password_salt VARCHAR(255) NOT NULL, PRIMARY KEY (id));

ALTER TABLE haikudepot.pkg ADD FOREIGN KEY (publisher_id) REFERENCES haikudepot.publisher (id);
ALTER TABLE haikudepot.repository ADD FOREIGN KEY (architecture_id) REFERENCES haikudepot.architecture (id);
ALTER TABLE haikudepot.pkg_version ADD FOREIGN KEY (architecture_id) REFERENCES haikudepot.architecture (id);
ALTER TABLE haikudepot.pkg_version ADD FOREIGN KEY (pkg_id) REFERENCES haikudepot.pkg (id);
ALTER TABLE haikudepot.pkg_version ADD FOREIGN KEY (repository_id) REFERENCES haikudepot.repository (id);
ALTER TABLE haikudepot.pkg_version_copyright ADD FOREIGN KEY (pkg_version_id) REFERENCES haikudepot.pkg_version (id);
ALTER TABLE haikudepot.pkg_version_localization ADD FOREIGN KEY (pkg_version_id) REFERENCES haikudepot.pkg_version (id);
ALTER TABLE haikudepot.pkg_version_license ADD FOREIGN KEY (pkg_version_id) REFERENCES haikudepot.pkg_version (id);
ALTER TABLE haikudepot.pkg_version_url ADD FOREIGN KEY (pkg_url_type_id) REFERENCES haikudepot.pkg_url_type (id);
ALTER TABLE haikudepot.pkg_version_url ADD FOREIGN KEY (pkg_version_id) REFERENCES haikudepot.pkg_version (id);

-- ------------------------------------------------------
-- MANUALLY CREATED SEQUENCES
-- ------------------------------------------------------

CREATE SEQUENCE haikudepot.repository_seq START WITH 7629 INCREMENT BY 1;
CREATE SEQUENCE haikudepot.architecture_seq START WITH 2862 INCREMENT BY 1;
CREATE SEQUENCE haikudepot.pkg_seq START WITH 9812 INCREMENT BY 10;
CREATE SEQUENCE haikudepot.pkg_version_url_seq START WITH 8364 INCREMENT BY 10;
CREATE SEQUENCE haikudepot.pkg_version_seq START WITH 2736 INCREMENT BY 10;
CREATE SEQUENCE haikudepot.pkg_version_localization_seq START WITH 4422 INCREMENT BY 10;
CREATE SEQUENCE haikudepot.pkg_version_copyright_seq START WITH 8684 INCREMENT BY 10;
CREATE SEQUENCE haikudepot.pkg_version_license_seq START WITH 3826 INCREMENT BY 10;
CREATE SEQUENCE haikudepot.pkg_url_type_seq START WITH 2235 INCREMENT BY 1;
CREATE SEQUENCE haikudepot.publisher_seq START WITH 9373 INCREMENT BY 1;
CREATE SEQUENCE haikudepot.user_seq START WITH 1247 INCREMENT BY 1;

-- ------------------------------------------------------
-- REFERENCE DATA
-- ------------------------------------------------------

INSERT INTO haikudepot.architecture (id,code) VALUES (nextval('architecture_seq'), 'x86_gcc2');
INSERT INTO haikudepot.architecture (id,code) VALUES (nextval('architecture_seq'), 'x86');
INSERT INTO haikudepot.architecture (id,code) VALUES (nextval('architecture_seq'), 'any');
INSERT INTO haikudepot.architecture (id,code) VALUES (nextval('architecture_seq'), 'source');

INSERT INTO haikudepot.pkg_url_type (id,code) VALUES (nextval('pkg_url_type_seq'), 'homepage');

-- ------------------------------------------------------
-- INDEXES
-- ------------------------------------------------------

CREATE UNIQUE INDEX architecture_idx01 ON haikudepot.architecture(code);
CREATE UNIQUE INDEX repository_idx01 ON haikudepot.repository(code);
CREATE UNIQUE INDEX pkg_idx01 ON haikudepot.pkg(name);
CREATE UNIQUE INDEX pkg_url_type_idx01 ON haikudepot.pkg_url_type(code);
CREATE UNIQUE INDEX publisher_idx01 ON haikudepot.publisher(code);
CREATE UNIQUE INDEX version_idx01 ON haikudepot.pkg_version(pkg_id, major, minor, micro, revision, pre_release);
CREATE UNIQUE INDEX user_idx01 ON haikudepot.user(nickname);

CREATE INDEX pkg_idx02 ON haikudepot.pkg(publisher_id);
CREATE INDEX pkg_version_idx02 ON haikudepot.pkg_version(repository_id);
CREATE INDEX pkg_version_idx03 ON haikudepot.pkg_version(architecture_id);
CREATE INDEX pkg_version_copyright_idx01 ON haikudepot.pkg_version_copyright(pkg_version_id);
CREATE INDEX pkg_version_license_idx01 ON haikudepot.pkg_version_license(pkg_version_id);
CREATE INDEX pkg_version_localization_idx01 ON haikudepot.pkg_version_localization(pkg_version_id);
CREATE INDEX pkg_version_url_idx01 ON haikudepot.pkg_version_url(pkg_url_type_id);
CREATE INDEX pkg_version_url_idx03 ON haikudepot.pkg_version_url(pkg_version_id);
CREATE INDEX repository_idx02 ON haikudepot.repository(architecture_id);

-- ------------------------------------------------------
