-- The existing natural languages are the "major" languages of the world such as
-- English, German, Spanish etc... so we should mark those ones as being "popular"
-- so that they might always been shown.

ALTER TABLE haikudepot.natural_language ADD COLUMN is_popular BOOLEAN;
UPDATE haikudepot.natural_language SET is_popular = true;
ALTER TABLE haikudepot.natural_language ALTER COLUMN is_popular SET NOT NULL;

-- Now I want to load in all of the other languages from the ISO-639 standard
-- from here; http://loc.gov/standards/iso639-2/ISO-639-2_utf-8.txt
-- transformed into SQL INSERT statements.

INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'aa','Afar',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'ab','Abkhazian',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'af','Afrikaans',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'ak','Akan',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'sq','Albanian',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'am','Amharic',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'ar','Arabic',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'an','Aragonese',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'hy','Armenian',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'as','Assamese',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'av','Avaric',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'ae','Avestan',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'ay','Aymara',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'az','Azerbaijani',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'ba','Bashkir',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'bm','Bambara',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'eu','Basque',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'be','Belarusian',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'bn','Bengali',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'bh','Bihari languages',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'bi','Bislama',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'bs','Bosnian',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'br','Breton',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'bg','Bulgarian',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'my','Burmese',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'ca','Catalan; Valencian',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'ch','Chamorro',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'ce','Chechen',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'cv','Chuvash',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'kw','Cornish',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'co','Corsican',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'cr','Cree',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'cs','Czech',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'da','Danish',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'dv','Divehi; Dhivehi; Maldivian',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'nl','Dutch; Flemish',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'dz','Dzongkha',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'eo','Esperanto',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'et','Estonian',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'ee','Ewe',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'fo','Faroese',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'fj','Fijian',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'fi','Finnish',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'fy','Western Frisian',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'ff','Fulah',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'ka','Georgian',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'gd','Gaelic; Scottish Gaelic',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'ga','Irish',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'gl','Galician',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'gv','Manx',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'el','Greek, Modern (1453-)',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'gn','Guarani',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'gu','Gujarati',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'ht','Haitian; Haitian Creole',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'ha','Hausa',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'he','Hebrew',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'hz','Herero',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'hi','Hindi',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'ho','Hiri Motu',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'hr','Croatian',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'hu','Hungarian',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'ig','Igbo',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'is','Icelandic',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'io','Ido',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'ii','Sichuan Yi; Nuosu',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'iu','Inuktitut',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'id','Indonesian',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'ik','Inupiaq',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'it','Italian',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'jv','Javanese',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'kl','Kalaallisut; Greenlandic',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'kn','Kannada',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'ks','Kashmiri',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'kr','Kanuri',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'kk','Kazakh',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'km','Central Khmer',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'ki','Kikuyu; Gikuyu',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'rw','Kinyarwanda',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'ky','Kirghiz; Kyrgyz',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'kv','Komi',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'kg','Kongo',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'ko','Korean',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'kj','Kuanyama; Kwanyama',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'ku','Kurdish',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'lo','Lao',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'la','Latin',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'lv','Latvian',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'li','Limburgan; Limburger; Limburgish',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'ln','Lingala',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'lt','Lithuanian',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'lb','Luxembourgish; Letzeburgesch',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'lu','Luba-Katanga',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'lg','Ganda',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'mk','Macedonian',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'mh','Marshallese',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'ml','Malayalam',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'mi','Maori',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'mr','Marathi',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'ms','Malay',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'mg','Malagasy',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'mt','Maltese',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'mn','Mongolian',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'na','Nauru',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'nv','Navajo; Navaho',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'nr','Ndebele, South; South Ndebele',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'nd','Ndebele, North; North Ndebele',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'ng','Ndonga',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'ne','Nepali',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'nn','Norwegian Nynorsk; Nynorsk, Norwegian',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'nb','Bokmål, Norwegian; Norwegian Bokmål',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'no','Norwegian',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'ny','Chichewa; Chewa; Nyanja',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'oc','Occitan (post 1500,false); Provençal',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'oj','Ojibwa',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'or','Oriya',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'om','Oromo',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'os','Ossetian; Ossetic',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'pa','Panjabi; Punjabi',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'fa','Persian',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'pi','Pali',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'pl','Polish',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'ps','Pushto; Pashto',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'qu','Quechua',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'rm','Romansh',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'ro','Romanian; Moldavian; Moldovan',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'rn','Rundi',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'sg','Sango',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'sa','Sanskrit',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'si','Sinhala; Sinhalese',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'sk','Slovak',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'sl','Slovenian',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'se','Northern Sami',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'sm','Samoan',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'sn','Shona',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'sd','Sindhi',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'so','Somali',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'st','Sotho, Southern',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'sc','Sardinian',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'sr','Serbian',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'ss','Swati',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'su','Sundanese',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'sw','Swahili',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'sv','Swedish',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'ty','Tahitian',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'ta','Tamil',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'tt','Tatar',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'te','Telugu',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'tg','Tajik',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'tl','Tagalog',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'th','Thai',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'bo','Tibetan',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'ti','Tigrinya',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'to','Tonga (Tonga Islands)',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'tn','Tswana',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'ts','Tsonga',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'tk','Turkmen',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'tr','Turkish',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'tw','Twi',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'ug','Uighur; Uyghur',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'uk','Ukrainian',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'ur','Urdu',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'uz','Uzbek',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'ve','Venda',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'vi','Vietnamese',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'vo','Volapük',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'cy','Welsh',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'wa','Walloon',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'wo','Wolof',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'xh','Xhosa',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'yi','Yiddish',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'yo','Yoruba',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'za','Zhuang; Chuang',false);
INSERT INTO haikudepot.natural_language (id,code,name,is_popular) VALUES (NEXTVAL('haikudepot.natural_language_seq'),'zu','Zulu',false);